:wheelchair: Bedre aria-labels for rader i admin-flate
navikt/mulighetsrommet pull request #1144
Opened 2023-02-27 19:24 UTC by sndrem

I forbindelse med en workshop med Bekk testet jeg admin-flate med voiceover på Mac og fant at vi har godt av noen eksplisitt aria-labels for radene for tiltakstyper og avtaler.

2023-02-28 06:33 UTC, taniaholst requested changes
Bra! Har bare en kommentar som går igjen noen steder, men bra at du tar tak i dette!

2023-02-28 06:33 UTC, taniaholst commented on frontend/mr-admin-flate/src/components/avtaler/Avtalerad.tsx
> +        aria-label={`Startdato ${formaterDato(avtale.startDato)}`}
Ser at de andre aria-labelene har kolon etter tittel, bør denne også ha det?

2023-02-28 06:33 UTC, taniaholst commented on frontend/mr-admin-flate/src/components/avtaler/Avtalerad.tsx
> +        aria-label={`Sluttdato ${formaterDato(avtale.sluttDato)}`}
Ser at de andre aria-labelene har kolon etter tittel, bør denne også ha det?

2023-02-28 06:33 UTC, taniaholst commented on frontend/mr-admin-flate/src/components/tiltakstyper/TiltakstypeRad.tsx
> +        aria-label={`Startdato ${formaterDato(tiltakstype.fraDato)}`}
Ser at de andre aria-labelene har kolon etter tittel, bør denne også ha det?

2023-02-28 06:33 UTC, taniaholst commented on frontend/mr-admin-flate/src/components/tiltakstyper/TiltakstypeRad.tsx
> +        aria-label={`Sluttdato ${formaterDato(tiltakstype.tilDato)}`}
Ser at de andre aria-labelene har kolon etter tittel, bør denne også ha det?

2023-03-01 07:03 UTC, sndrem commented on frontend/mr-admin-flate/src/components/avtaler/Avtalerad.tsx
> +        aria-label={`Startdato ${formaterDato(avtale.startDato)}`}
Fikset så vi er konsekvente. Rent praktisk så leste ikke voiceover noe forskjellig med eller uten kolon

2023-03-01 07:25 UTC, taniaholst approved these changes

2023-03-01 07:25 UTC, merged