Amt filter
navikt/mulighetsrommet pull request #3226
Opened 2024-02-06 12:20 UTC by taniaholst

2024-02-06 13:35 UTC, sndrem commented on frontend/mulighetsrommet-veileder-flate/src/apps/nav/filtrering/NavFilterTags.tsx
> +          handleClick={() => setFilter({ ...filter, search: "" })}
Burde `handleClick` egentlig døpes om til `onClose` siden det er den funksjonen som kjører når man X'er ut filterverdien?

2024-02-06 13:38 UTC, sndrem commented on frontend/mulighetsrommet-veileder-flate/src/apps/nav/views/NavArbeidsmarkedstiltakOversikt.tsx
> +              header="Du må filtrere på en NAV-enhet og en innsatsgruppe for å se tiltaksgjennomføringer"
Veldig pirk, men skulle det stått `minst én NAV-enhet` istedenfor `...på en NAV-enhet`?

2024-02-06 13:40 UTC, sndrem commented on frontend/mulighetsrommet-veileder-flate/src/components/tags/NavEnhetTag.tsx
> +  const [, setFilter] = useArbeidsmarkedstiltakFilterUtenBrukerIKontekst();
Blir det korrekt å bruke `useArbeidsmarkedstiltakFilterUtenBrukerIKontekst`? Hvordan blir det når man har en bruker i kontekst?

2024-02-06 13:42 UTC, sndrem requested changes
Noen småting jeg lurer på

2024-02-06 15:04 UTC, sndrem submitted a review, later dismissed

2024-02-07 06:35 UTC, taniaholst commented on frontend/mulighetsrommet-veileder-flate/src/apps/nav/views/NavArbeidsmarkedstiltakOversikt.tsx
> +              header="Du må filtrere på en NAV-enhet og en innsatsgruppe for å se tiltaksgjennomføringer"
Hvorfor ble denne endret tilbake?

2024-02-07 06:36 UTC, taniaholst commented on frontend/mulighetsrommet-veileder-flate/tests/nav-arbeidsmarkedstiltak.spec.ts
> +    );
Siden teksten potensielt kan endres, er det ikke da dumt å lete etter tekst?

2024-02-07 06:37 UTC, taniaholst reviewed
Småkommentarer

2024-02-07 07:25 UTC, merged